// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfalvcczrbfuzoscwojb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmYWx2Y2N6cmJmdXpvc2N3b2piIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDcwNDgsImV4cCI6MjA2MDAyMzA0OH0.3pLQ1SUbJaYYFHm9OWsP4Z2aVqtP0BUjsXwcfRAa4P4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);